version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh
        
aliases:

  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly --depth 1 git@github.com:CDAT/cdat workspace/cdat
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
      
  - &create_conda_env
    name: create_conda_env
    environment:
       PKGS: "cdms2 cdat_info testsrunner mesalib matplotlib numpy=1.13 vcs 'proj4<5'"
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       if [[ $PY_VER = "py2" ]]; then
          conda create -q -n $PY_VER $CHANNELS $PKGS $FFMPEG "python<3"
       else
          conda create -q -n $PY_VER $CHANNELS $PKGS $FFMPEG "python>3" $COVERAGE_PKGS
       fi

  - &setup_thermo
    name: setup_thermo
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       source activate $PY_VER
       python setup.py install
       rm -rf build

  - &run_thermo_tests
    name: run_thermo_tests
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       mkdir tests_png
       mkdir tests_html
       source activate $PY_VER
       python run_tests.py -v2 -n 2 -H $COVERAGE
       RESULT=$?
       echo "*** $PY_VER test result: "${RESULT} 
       exit $RESULT

  - &run_coveralls
    name: run_coveralls
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       source activate $PY_VER
       coveralls
       source deactivate

  - &conda_upload
    name: conda_upload
    environment:
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
       PKG_NAME: "thermo"
       USER: "cdat"
       VERSION: "8.0"
       LABEL: "nightly"
    command: |
       if [[ $CIRCLE_BRANCH != 'master' ]]; then
          exit 0
       fi
       export PATH=${HOME}/project/$WORKDIR/miniconda/bin:$PATH
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       if [[ -d $PKG_NAME ]]; then
          rm -rf $PKG_NAME
       fi
       ln -s ../recipe $PKG_NAME
       python ./prep_for_build.py -l $VERSION
       if [[ $PY_VER = 'py2' ]]; then
          conda build $PKG_NAME $CHANNELS
       else
          conda build $PKG_NAME $CHANNELS --python=3.6
       fi
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/$OS/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

jobs:
  macos_thermo_py2:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "test_macos_thermo_py2"
      OS: "osx-64"
      PY_VER: "py2"
      FFMPEG: "'ffmpeg>4' 'libpng>1.6.34'"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  macos_thermo_py3:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_thermo_py3"
      OS: "osx-64"
      PY_VER: "py3"
      FFMPEG: "'ffmpeg>4' 'libpng>1.6.34'"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  linux_thermo_py2:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_thermo_py2"
      OS: "linux-64"
      PY_VER: "py2"
      FFMPEG: "ffmpeg"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  linux_thermo_py3:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_thermo_py3"
      OS: "linux-64"
      PY_VER: "py3"
      FFMPEG: "ffmpeg"
      COVERAGE: "-c tests/coverage.json"
      COVERAGE_PKGS: "coverage coveralls"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *run_coveralls
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

workflows:
  version: 2
  thermo:
    jobs:
      - macos_thermo_py2
      - macos_thermo_py3:
           requires:
              - macos_thermo_py2
      - linux_thermo_py2
      - linux_thermo_py3:
           requires:
              - linux_thermo_py2
