version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh
        
aliases:

  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly --depth 1 git@github.com:CDAT/cdat workspace/cdat
      ls workspace/cdat
      # following will install miniconda3 under $WORKDIR/miniconda/bin
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
      
  - &create_conda_env
    name: create_conda_env
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       conda create -q -n py2 -c cdat/label/nightly -c conda-forge -c cdat cdms2 nose flake8 mesalib image-compare matplotlib numpy=1.13 vcs "proj4<5" "python<3"
       conda create -q -n py3 -c cdat/label/nightly -c conda-forge -c cdat cdms2 nose flake8 mesalib image-compare matplotlib numpy=1.13 vcs "proj4<5" "python>3"

  - &setup_thermo
    name: setup_thermo
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export UVCDAT_ANONYMOUS_LOG=False
       source activate py2
       python setup.py install
       source activate py3
       rm -rf build
       python setup.py install

  - &run_thermo_tests
    name: run_thermo_tests
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export UVCDAT_ANONYMOUS_LOG=False
       source activate py2
       python run_tests.py -v2 -n 2 -H
       RESULT=$?
       echo "*** py2 test result: "${RESULT} 
       source activate py3
       python run_tests.py -n 2 -H
       echo "*** py3 test result: "$?
       RESULT=$(( $RESULT + $? ))
       exit $RESULT

  - &conda_upload
    name: conda_upload
    command: |
       export PATH=${HOME}/project/$WORKDIR/miniconda/bin:$PATH
       echo "WORKDIR: "$WORKDIR
       pwd
       ls $WORKDIR
       which conda
       export PKG_NAME=thermo
       export USER=cdat
       export VERSION=8.0
       export LABEL=nightly
       mkdir conda_build
       cd conda_build
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       python ./prep_for_build.py -l $VERSION
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat 
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat --python=3.6
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/$OS/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

jobs:

  macos_thermo:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_thermo"
      OS: "osx-64"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  linux_thermo:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_thermo"
      OS: "linux-64"
    steps:
      - checkout
      - run: *setup_miniconda 
      - run: *create_conda_env
      - run: *setup_thermo
      - run: *run_thermo_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

workflows:
  version: 2
  thermo:
    jobs:
      - macos_thermo:
          filters:
            branches:
              only: master
      - linux_thermo:
          filters:
            branches:
              only: master
